# core/reporter.py
import json
import os
from datetime import datetime
from pathlib import Path

class ReportGenerator:
    def __init__(self, target, module_name):
        self.target = target
        self.module = module_name
        self.timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.report_dir = Path("reports") / module_name
        self.report_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_html(self, data, findings):
        """تولید گزارش HTML زیبا"""
        html_template = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>CyberHUD - {self.module} Report</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; background: #0a0e27; color: #fff; }}
                .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px; border-radius: 10px; }}
                .critical {{ background: #ff4444; padding: 10px; border-radius: 5px; }}
                .high {{ background: #ff8800; padding: 10px; border-radius: 5px; }}
                .medium {{ background: #ffbb33; padding: 10px; border-radius: 5px; }}
                .low {{ background: #00C851; padding: 10px; border-radius: 5px; }}
                table {{ width: 100%; border-collapse: collapse; }}
                th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }}
                .footer {{ margin-top: 20px; text-align: center; color: #888; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>🔍 CyberHUD Security Report</h1>
                <h2>Module: {self.module}</h2>
                <h3>Target: {self.target}</h3>
                <p>Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
            </div>
            
            <h2>📊 Executive Summary</h2>
            <div style="display: flex; gap: 10px;">
                <div class="critical">Critical: {len(findings.get('critical', []))}</div>
                <div class="high">High: {len(findings.get('high', []))}</div>
                <div class="medium">Medium: {len(findings.get('medium', []))}</div>
                <div class="low">Low: {len(findings.get('low', []))}</div>
            </div>
            
            <h2>🔬 Detailed Findings</h2>
            <table>
                <tr>
                    <th>Severity</th>
                    <th>Finding</th>
                    <th>Description</th>
                </tr>
                {self._generate_rows(findings)}
            </table>
            
            <h2>📝 Raw Data</h2>
            <pre>{json.dumps(data, indent=2)}</pre>
            
            <div class="footer">
                Generated by CyberHUD - Marijuana1999 | https://github.com/Marijuana1999
            </div>
        </body>
        </html>
        """
        
        filename = self.report_dir / f"{self.target}_{self.timestamp}.html"
        with open(filename, 'w') as f:
            f.write(html_template)
        
        return filename
    
    def _generate_rows(self, findings):
        rows = ""
        for severity, items in findings.items():
            for item in items:
                rows += f"""
                <tr>
                    <td><span class="{severity}">{severity.upper()}</span></td>
                    <td>{item.get('title', 'N/A')}</td>
                    <td>{item.get('description', 'N/A')}</td>
                </tr>
                """
        return rows